### PR TITLE
Connman tethering support

### PR DESCRIPTION
**Pull request by monich**
Requires https://github.com/mer-packages/connman/pull/214. Won't work with the upstream usb gadget plugin.

### CODE REVIEW

**Comment by monich** [comment]
Please suggest the name for the config file so that I don't have to guess.

The necessary configure switch (`--enable-connman`) is already in place, new behavior is triggered by `connman_tethering` entry in the config file which provides the path of the tethering technology.

**Comment by philippedeswert** [comment]
connection_sharing-android-connman.ini maybe. Well looking at things I should probably also get some naming scheme going as I have switched - and _ in some of them.

**Comment by monich** [comment]
Renamed the file, updated the PR.

The config package name is now `usb-moded-connection-sharing-android-connman-config`. It's a bit too long for my liking but I hope you like it.

**Comment by philippedeswert** [comment]
Yeah it gets long but otoh it is immediately clear what it is for.

**Pull request merged**
